// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ15jHyft4nI-E2oUu43EBWS-kk7sF-h0',
    appId: '1:251231609452:web:7ffc54ef924b7961d16e49',
    messagingSenderId: '251231609452',
    projectId: 'petbook-app-88a65',
    authDomain: 'petbook-app-88a65.firebaseapp.com',
    storageBucket: 'petbook-app-88a65.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdtaW8kMUby-lp06LvUw8A08zIXpC_Aww',
    appId: '1:251231609452:android:b2cf7320348c4debd16e49',
    messagingSenderId: '251231609452',
    projectId: 'petbook-app-88a65',
    storageBucket: 'petbook-app-88a65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVjql_0OBfz6rhVvKSnyAPfpI8fFDDUQk',
    appId: '1:251231609452:ios:d9cb25f179e91221d16e49',
    messagingSenderId: '251231609452',
    projectId: 'petbook-app-88a65',
    storageBucket: 'petbook-app-88a65.firebasestorage.app',
    iosBundleId: 'com.example.petbookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVjql_0OBfz6rhVvKSnyAPfpI8fFDDUQk',
    appId: '1:251231609452:ios:d9cb25f179e91221d16e49',
    messagingSenderId: '251231609452',
    projectId: 'petbook-app-88a65',
    storageBucket: 'petbook-app-88a65.firebasestorage.app',
    iosBundleId: 'com.example.petbookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ15jHyft4nI-E2oUu43EBWS-kk7sF-h0',
    appId: '1:251231609452:web:d88d05d70dfd1cfbd16e49',
    messagingSenderId: '251231609452',
    projectId: 'petbook-app-88a65',
    authDomain: 'petbook-app-88a65.firebaseapp.com',
    storageBucket: 'petbook-app-88a65.firebasestorage.app',
  );
}
